# SUSE Rancher Setup - external configuration
# The commented keys will be loaded into the application configuration.
# Only documented keys are accepted.

shared:

  # Which workflow is running?
  # Which engines are loaded for this workflow?
  # * Order determines menu order
  # * Engines without UI components should be last

  # Rancher on EKS workflow
  workflow: RancherOnEks
  engines:
    - AWS
    - ShirtSize
    - PreFlight
    - RancherOnEks
    - Helm
  # Rancher on AKS workflow
  # workflow: RancherOnAks
  # engines:
  #   - Azure
  #   - ShirtSize
  #   - PreFlight
  #   - RancherOnAks
  #   - Helm

  # Where are we installing Rancher from? (passed to _helm_)
  rancher:
    repo_name: rancher-stable
    repo_url: https://releases.rancher.com/server-charts/stable
    chart: rancher-stable/rancher
    release_name: rancher-stable
    version: 2.7.6

  # What version of kubernetes will be deployed?
  # https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-6/
  rancher_on_eks:
    k8s_version: "1.26"
  rancher_on_aks:
    k8s_version: "1.26"
