---
http_interactions:
- request:
    method: post
    uri: https://login.microsoftonline.com/[tenant]/oauth2/token
    body:
      encoding: UTF-8
      string: grant_type=client_credentials&client_id=[app_id]&client_secret=[password_encoded]&resource=https%3A%2F%2Fmanagement.azure.com%2F
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (linux x86_64) ruby/3.1.2p20
      Content-Length:
      - '182'
      Content-Type:
      - application/x-www-form-urlencoded
      Host:
      - login.microsoftonline.com
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-store, no-cache
      Pragma:
      - no-cache
      Content-Type:
      - application/json; charset=utf-8
      Expires:
      - "-1"
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      P3p:
      - CP="DSP CUR OTPi IND OTRi ONL FIN"
      X-Ms-Request-Id:
      - 9cb4af90-6b76-47ed-8565-450c08f9ad01
      X-Ms-Ests-Server:
      - 2.1.16150.3 - WEULR1 ProdSlices
      X-Xss-Protection:
      - '0'
      Set-Cookie:
      - fpc=Ak4U-5hlXGdGkTxKu1nNKZDQZtlFAQAAALC4idwOAAAA; expires=Fri, 06-Oct-2023
        00:02:56 GMT; path=/; secure; HttpOnly; SameSite=None
      - stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
      - x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
      Date:
      - Wed, 06 Sep 2023 00:02:56 GMT
      Content-Length:
      - '1468'
    body:
      encoding: UTF-8
      string: '{"token_type":"Bearer","expires_in":"3599","ext_expires_in":"3599","expires_on":"1693962176","not_before":"1693958276","resource":"https://management.azure.com/","access_token":"[token]"}'
  recorded_at: Wed, 06 Sep 2023 00:02:56 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/[subscription]/providers/Microsoft.ContainerService/locations/westus3/kubernetesVersions?api-version=2023-07-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (linux x86_64) ruby/3.1.2p20
      Authorization:
      - "[token]"
      Host:
      - management.azure.com
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache
      Pragma:
      - no-cache
      Content-Length:
      - '985'
      Content-Type:
      - application/json
      Expires:
      - "-1"
      X-Ms-Ratelimit-Remaining-Subscription-Reads:
      - '11997'
      X-Ms-Correlation-Request-Id:
      - 6d8bf9b3-f35b-4d6e-972c-b775ace0a5d1
      X-Ms-Request-Id:
      - 71b13dd3-9503-42c3-a01e-c4d2d3b4afc2
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Ms-Routing-Request-Id:
      - WESTUS:20230906T000256Z:6d8bf9b3-f35b-4d6e-972c-b775ace0a5d1
      X-Cache:
      - CONFIG_NOCACHE
      X-Msedge-Ref:
      - 'Ref A: 9E1FEBC7854043A9BAC421392E036C0B Ref B: CO6AA3150219053 Ref C: 2023-09-06T00:02:56Z'
      Date:
      - Wed, 06 Sep 2023 00:02:56 GMT
    body:
      encoding: UTF-8
      string: |-
        {
          "values": [
           {
            "version": "1.25",
            "capabilities": {
             "supportPlan": [
              "KubernetesOfficial"
             ]
            },
            "patchVersions": {
             "1.25.11": {
              "upgrades": [
               "1.26.6",
               "1.26.3"
              ]
             },
             "1.25.6": {
              "upgrades": [
               "1.26.6",
               "1.26.3",
               "1.25.11"
              ]
             }
            }
           },
           {
            "version": "1.27",
            "capabilities": {
             "supportPlan": [
              "KubernetesOfficial",
              "AKSLongTermSupport"
             ]
            },
            "patchVersions": {
             "1.27.1": {
              "upgrades": [
               "1.27.3"
              ]
             },
             "1.27.3": {
              "upgrades": []
             }
            }
           },
           {
            "version": "1.26",
            "capabilities": {
             "supportPlan": [
              "KubernetesOfficial"
             ]
            },
            "patchVersions": {
             "1.26.3": {
              "upgrades": [
               "1.27.3",
               "1.27.1",
               "1.26.6"
              ]
             },
             "1.26.6": {
              "upgrades": [
               "1.27.3",
               "1.27.1"
              ]
             }
            }
           }
          ]
         }
  recorded_at: Wed, 06 Sep 2023 00:02:57 GMT
recorded_with: VCR 6.1.0
